create table TIMESHEETS
(
	ID				VARCHAR(20)	PRIMARY KEY,
	EMPLOYEEID		VARCHAR(20)	NOT NULL,
	DWORKDATE		DATETIME	NOT NULL,
	VSTATUS			VARCHAR(2),
	DSTARTWORK		DATETIME	NOT NULL,
	DENDWORK		DATETIME	NOT NULL,
	DSTARTOT		DATETIME,
	DENDOT			DATETIME,
	VDESCRIPTION	VARCHAR(255),
	DCREA			DATETIME,
	VCREA			VARCHAR(20),
	DMODI			DATETIME,
	VMODI			VARCHAR(20)
);

create table EMPLOYEES
(
	ID				VARCHAR(20) PRIMARY KEY,
	NAME			VARCHAR(50) NOT NULL,
	ADDRESS			VARCHAR(255),
	EMAIL			VARCHAR(100),
	PHONENUMBER		VARCHAR(100),
	SALARY			INT,
	POSITIONID		VARCHAR(5),
	BOOTCAMP		VARCHAR(5),
	PROJECTID		VARCHAR(10),
	DCREA			DATETIME,
	VCREA			VARCHAR(20),
	DMODI			DATETIME,
	VMODI			VARCHAR(20)
);

create table POSITIONS
(
	POSITIONID		VARCHAR(5)	PRIMARY KEY,
	POSITION		VARCHAR(100) NOT NULL,
	DCREA			DATETIME,
	VCREA			VARCHAR(20),
	DMODI			DATETIME,
	VMODI			VARCHAR(20)
);

create table PROJECTS
(
	PROJECTID		VARCHAR(10)	PRIMARY KEY,
	VCLNAME			VARCHAR(255),
	VCLADDRESS		VARCHAR(255),
	DCREA			DATETIME,
	VCREA			VARCHAR(20),
	DMODI			DATETIME,
	VMODI			VARCHAR(20)
);