//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtriumXsisV4.WebApps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        public string ID { get; set; }
        public string NAME { get; set; }
        public string ADDRESS { get; set; }
        public string EMAIL { get; set; }
        public string PHONENUMBER { get; set; }
        public Nullable<int> SALARY { get; set; }
        public string POSITIONID { get; set; }
        public string BOOTCAMP { get; set; }
        public string PROJECTID { get; set; }
        public Nullable<System.DateTime> DCREA { get; set; }
        public string VCREA { get; set; }
        public Nullable<System.DateTime> DMODI { get; set; }
        public string VMODI { get; set; }
    
        public virtual POSITION POSITION { get; set; }
        public virtual PROJECT PROJECT { get; set; }
    }
}
