//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtriumXsisV4.WebApps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSITION
    {
        public string POSITIONID { get; set; }
        public string VPOSNAME { get; set; }
        public Nullable<System.DateTime> DCREA { get; set; }
        public string VCREA { get; set; }
        public Nullable<System.DateTime> DMODI { get; set; }
        public string VMODI { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
    }
}
