//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtriumXsisV4.WebApps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIMESHEET
    {
        public string ID { get; set; }
        public string EMPLOYEEID { get; set; }
        public System.DateTime DWORKDATE { get; set; }
        public string VSTATUS { get; set; }
        public System.DateTime DSTARTWORK { get; set; }
        public System.DateTime DENDWORK { get; set; }
        public Nullable<System.DateTime> DSTARTOT { get; set; }
        public Nullable<System.DateTime> DENDOT { get; set; }
        public string VDESCRIPTION { get; set; }
        public Nullable<System.DateTime> DCREA { get; set; }
        public string VCREA { get; set; }
        public Nullable<System.DateTime> DMODI { get; set; }
        public string VMODI { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
    }
}
